---
- name: Настроить внутренний DNS
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: "DNS={{ hostvars[groups['net_service'][0]].ansible_host }}"
  notify: restart systemd-resolved

- name: Применить изменения
  ansible.builtin.meta: flush_handlers