[all:vars]
ansible_user=admin
admin_user=admin
timezone=Europe/Moscow
locale=en_US.UTF-8
proxmox=192.168.0.200
management_ip=10.0.0.2

[docker_nodes]
docker ansible_host=10.0.0.105 bootstrap_user=root

[net_service]
dns ansible_host=10.0.0.110 bootstrap_user=root

[nginx_nodes]
nginx ansible_host=10.0.0.107 bootstrap_user=root

[gitlab_node]
gitlab ansible_host=10.0.0.115 bootstrap_user=root

[hq]
hq ansible_host=10.0.0.2 ansible_connection=local

[kuber]
master-node ansible_host=10.0.0.120 bootstrap_user=root
worker-node ansible_host=10.0.0.121 bootstrap_user=root

; [vm_nodes]
; 10.0.0.10 bootstrap_user=glebuga 
; 10.0.0.11 bootstrap_user=glebuga