
nginx_ip:
  host: nginx
  groups: [nginx_nodes]
  bootstrap: true

docker_ip:
  host: docker
  groups: [docker_nodes]
  bootstrap: true

dns_ip:
  host: dns
  groups: [net_service]
  bootstrap: true

gitlab_ip:
  host: gitlab
  groups: [gitlab_node]
  bootstrap: true

# --- VMs (dict keyed by vm_id) ---
k3s_vm_ips:
  host_prefix: k3s-
  groups: [kuber]
  bootstrap: false

ubuntu_vm_ips:
  host_prefix: vm-
  groups: [ubuntu_vms]
  bootstrap: false

# Example
# centos_vm_ips:
#   host_prefix: cos-
#   groups: [centos_vms]
#   bootstrap: false
#   user: centos_admin

# monitoring_ip:
#   host: monitoring
#   groups: [monitoring_group]
#   bootstrap: true

harbor_ip:
  host: harbor
  groups: [harbor_nodes]
  bootstrap: true
