---
- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: yes

- name: Deploy Docker rules
  ansible.builtin.template:
    src: docker.rules.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups["docker_nodes"]
  notify: Restore iptables

- name: Deploy Nginx rules
  ansible.builtin.template:
    src: nginx.rules.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups["nginx_nodes"]
  notify: Restore iptables

- name: Deploy DNS rules
  ansible.builtin.template:
    src: net-services.rules.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: "0644"
  when: inventory_hostname in groups["net_service"]
  notify: Restore iptables

- name: Apply changes
  ansible.builtin.meta: flush_handlers