---
# FQDN Harbor, совпадающий с CN TLS-сертификата.
harbor_hostname: "harbor.home.local"

# Версия Harbor (официальный релиз docker compose).
harbor_version: "v2.10.1"

harbor_offline_installer: true
harbor_local_installer_src: "{{ ansible_modular_root }}/harbor-installer/harbor-offline-installer-{{ harbor_version }}.tgz"

# Сетевые порты.
harbor_http_port: 80
harbor_https_port: 443

# Каталог данных Harbor на хосте.
harbor_data_volume: "/data"

# Каталог с TLS-сертификатом внутри хоста Harbor.
harbor_cert_dir: "/data/cert"

# Имена файлов сертификата (должны лежать в harbor_local_cert_src).
harbor_cert_file: "harbor.crt"
harbor_key_file: "harbor.key"

# Локальный путь (на управляющей машине) к сертификатам.
# Роль только КОПИРУЕТ их, не генерирует.
harbor_local_cert_src: "{{ ansible_modular_root }}/certs/harbor"

# Опциональные компоненты Harbor.
harbor_with_trivy: true
harbor_with_notary: false
harbor_with_chartmuseum: false

# Имя проекта, который роль создаёт после установки (вместо library).
harbor_project_name: "gitlab"

# Секреты (harbor_admin_password, harbor_db_password) определены в vault.yml
