---
- name: Установить nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Включить и запустить nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true

- name: Удалить дефолтный сайт
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Развернуть конфигурацию reverse proxy
  ansible.builtin.template:
    src: homelab.conf.j2
    dest: /etc/nginx/sites-available/homelab.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart nginx

- name: Включить сайт
  ansible.builtin.file:
    src: /etc/nginx/sites-available/homelab.conf
    dest: /etc/nginx/sites-enabled/homelab.conf
    state: link
  notify: restart nginx

- name: Проверить конфигурацию nginx
  ansible.builtin.command: nginx -t
  changed_when: false

- name: Применить изменения
  ansible.builtin.meta: flush_handlers