---
# Базовая настройка ОС, применяется ко всем хостам после bootstrap.
common_packages:
  - curl
  - vim
  - htop
  - tree
  # Раскомментируем по мере необходимости:
  # - git
  # - jq
  # - tmux
  # - wget
  # - ca-certificates
  # - gnupg
  # - lsb-release
  # - acl
  # - net-tools
  # - python3
  # - sudo
  # - unattended-upgrades

# Не обновлять установленные пакеты.
common_upgrade: false
common_upgrade_mode: "dist"

# Базовый .bashrc для admin.
common_shell_config: false

common_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
