---
- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker.io
    state: present
    update_cache: true

- name: Enable and launch Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Launch container app1
  community.docker.docker_container:
    name: app1
    image: traefik/whoami
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8081:80"

- name: Launch containerapp2
  community.docker.docker_container:
    name: app2
    image: traefik/whoami
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8082:80"